### ISSUE TITLE
Remove the second class from the icons property

### ISSUE THREAD

**Issue by RndFooBar** [vertexclique/tokamak#47]
Adding a Button with two icons propriety (like [here][1]) causes this [error][2].
[Detailled explanation][3].

[1]: https://github.com/vertexclique/tokamak/blob/3230f6ebd260f8c8463cb52c6fd8d5f330cf5ce6/lib/tokamak.coffee#L125
[2]: https://github.com/suda/tool-bar/issues/149
[3]: https://github.com/suda/tool-bar/issues/148#issuecomment-230169317

**Comment by yuleugim** [comment]
Can confirm on the latest tokomak version 0.2.7, and tool-bar version 1.0.0

The issue here is that tokamak is not adhering to tool-bar's `.addButton` method syntax. Proper usage of the method is documented in the readme: https://github.com/suda/tool-bar

So instead of:
```
@toolBar.addButton
      icon: 'ion ion-hammer'
      callback: 'tokamak:build'
      tooltip: 'Build'
```
There should be no prefixes and the icon set should be called separately:
```
@toolBar.addButton
      icon: 'hammer'
      callback: 'tokamak:build'
      tooltip: 'Build'
      iconset: 'ion'
```
Doing this for all of the non-Octicons icons (the default icon set for tool-bar) fixed it for me.

**Comment by dizergin** [comment]
yuleugim , it works for me too
